name: "CI"

on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Building and Pushing the Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Connect to container registry (dockerhub)
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build, tag and push image
      id: build
      run: |
        # Build a docker container and push it to CR
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        docker build -t shabbirsaifee/railsapp:${GITHUB_REF##*/}-$git_hash .
        echo "Pushing image to CR..."
        docker push shabbirsaifee/railsapp:${GITHUB_REF##*/}-$git_hash
        echo "::set-output name=IMAGE_TAG::${GITHUB_REF##*/}-$git_hash"
        echo "::set-output name=image::shabbirsaifee/railsapp:${GITHUB_REF##*/}-$git_hash"

    - name: Trigger Azure Devops Pipeline
      uses: Azure/pipelines@v1
      with:
        azure-devops-project-url: 'https://dev.azure.com/ssaifee1992/azure-devops-kubernetes'
        azure-pipeline-name: 'control' # name of the Azure pipeline to be triggered
        azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
        azure-pipeline-variables:  '{"tag": "${{ steps.build.outputs.IMAGE_TAG }}"}' # optional stringified json
